### ISSUE TITLE
[Suggestion] Implement Issue template in GitHub

### ISSUE THREAD

**Issue by Philip-Clark** [club-40/odin-pantry#33]
## Description
I propose we implement issue templates to make issues more uniform and informative

## Tasks

- [x] Create Issue templates for common issue types.

## Aditional items
- For a quick demo, feel free to create an issue in the following repository (https://github.com/Philip-Clark/sprintsInProjectTest/issues)

**Comment by Philip-Clark** [comment]
@RyanMcEntire Am I good to add templates? I've got some time and have set them up before.
I can also address the PR templates as mentioned in issue #41.

Just let me know if this is something you see value in.

**Comment by RyanMcEntire** [comment]
@Philip-Clark Yeah, this seems great. This will probably help a lot as we'll need to make a lot of issues for upcoming tasks.

**Comment by Philip-Clark** [comment]
@RyanMcEntire I've implemented Issue templates and submitted a Pr that is awaiting review. #42
After making any suggested changes and getting approval, I will close this issue as complete

**Comment by Philip-Clark** [comment]
PR #42 merged for this feature. Closing Issue
